#ifndef OPTIONS_H
#define OPTIONS_H

#define HOLDDURATION		20
#define MOVEPIXELS		15
#define ZOOMFACTOR		0.1

#define CTRL_PDF_LEFT		FZ_CTRL_LEFT
#define CTRL_PDF_RIGHT		FZ_CTRL_RIGHT
#define CTRL_PDF_UP		FZ_CTRL_UP
#define CTRL_PDF_DOWN		FZ_CTRL_DOWN
#define CTRL_PDF_ZOOM_IN	FZ_CTRL_CIRCLE
#define CTRL_PDF_ZOOM_OUT	FZ_CTRL_CROSS
#define CTRL_PDF_PG_UP		FZ_CTRL_RTRIGGER
#define CTRL_PDF_PG_DN		FZ_CTRL_LTRIGGER
#define CTRL_PDF_PG_LARGE_UP	FZ_CTRL_TRIANGLE
#define CTRL_PDF_PG_LARGE_DN	FZ_CTRL_SQUARE
#define CTRL_PDF_EXIT		FZ_CTRL_SELECT
#define CTRL_PDF_OPTIONS	FZ_CTRL_START

#define RGB(r,g,b) ((((b>>3) & 0x1F)<<10)|(((g>>3) & 0x1F)<<5)|(((r>>3) & 0x1F)<<0)|0x8000)

#define	COLOR_BG		RGB(0,0,0)
#define COLOR_FRAME		RGB(0xB3,0x00,0x00)
#define COLOR_BOX		RGB(0x99,0x22,0x22)
#define COLOR_TEXT		RGB(0xFF,0xBF,0xBF)
#define COLOR_COMMENTS		RGB(0xFF,0x80,0x80)


#endif
